#cloud-config


hostname: swarmworker-{{ STR_REPLACE(".", "-", REMOTE_IP()) }}
ssh_authorized_keys:
  - {{ TRIM(FILE("/root/rsa_public_key")) }}
  - {{ TRIM(FILE("/root/id_rsa.pub")) }}

write_files:
  - path: "/root/worker_join_token"
    owner: core:root
    content: {{ TRIM(FILE("/root/worker_join_token")) }}


write_files:
  - path: "/etc/environment"
    permissions: '0655'
    owner: core:root
    content: |
      COREOS_PRIVATE_IPV4={{ REMOTE_IP() }}
      PXE_SERVER_IP={{ ENV("PXE_SERVER_IP") }}

coreos:
  units:
    - name: swarm-join.service
      command: start
      content: |
        [Unit]
        Description=Docker Master
        After=sysinit.target
        Requires=docker.service

        [Service]
        EnvironmentFile=/etc/environment
        ExecStart=/bin/bash -c "docker swarm join --token $(cat /root/worker_join_token) $PXE_SERVER_IP:2377"




