#cloud-config


hostname: swarmworker-{{ STR_REPLACE(".", "-", REMOTE_IP()) }}
ssh_authorized_keys:
  - {{ TRIM(FILE("/root/rsa_public_key")) }}

write_files:
  - path: "/root/worker_join_token"
    owner: core:root
    content: {{ TRIM(FILE("/root/worker_join_token")) }}

write_files:
  - path: "/root/rsa_public_key"
    owner: core:root
    content: {{ TRIM(FILE("/root/rsa_public_key")) }}

write_files:
  - path: "/root/config"
    owner: core:root
    content: {{ TRIM(FILE("/root/config")) }}

write_files:
  - path: "/etc/environment"
    permissions: '0655'
    owner: core:root
    content: |
      COREOS_PRIVATE_IPV4={{ REMOTE_IP() }}
      PXE_SERVER_IP={{ ENV("COREOS_PRIVATE_IPV4") }}
      DHCP_RANGE={{ ENV("DHCP_RANGE") }}

write_files:
  - path: "/etc/exports"
    permissions: '0655'
    owner: core:root
    content: |
      /srv/nfs 10.16.0.0/24(rw,async,no_subtree_check,no_root_squash,fsid=0)

write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
coreos:
  units:
    - name: rpc-statd.service
      command: start
      enable: true
    - name: mnt.mount
      command: start
      content: |
        [Mount]
        What={{ ENV("NFS_MOUNT") }}
        Where=/mnt
        Type=nfs

write_files:
  - path: /var/lib/iptables/rules-save
    permissions: 0644
    owner: root:root
    content: |
      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -A INPUT -s 10.0.0.0/8 -d 10.0.0.0/8 -j ACCEPT
      -I INPUT -d 224.0.0.0/8 -p vrrp -j ACCEPT
      -A INPUT -i lo -j ACCEPT
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
      -A INPUT -d 0.0.0.0/0 -j DROP
      COMMIT

coreos:
  units:
    - name: iptables-restore.service
      command: start
      enable: true

    - name: swarm-join.service
      command: start
      content: |
        [Unit]
        Description=Docker Master
        After=docker.service
        Requires=docker.service
        [Service]
        EnvironmentFile=/etc/environment
        ExecStart=/bin/bash -c "docker swarm join --token $(cat /root/worker_join_token) $PXE_SERVER:2377 && docker run --net=host -e NFS_MOUNT={{ ENV("NFS_MOUNT") }} -e MODE=WORKERJOIN -v /root/config:/root/config -v /root/worker_join_token:/root/worker_join_token -v /root/rsa_public_key:/root/rsa_public_key --name coreos-pxe-swarm dermatthes/coreos-pxe-swarm"

    - name: format-ephemeral.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        After=sysinit.target
        Requires=sysinit.target
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/disk/by-label/COREOS_ROOT
        ExecStart=/usr/sbin/mkfs.ext4 -L COREOS_ROOT -F /dev/disk/by-label/COREOS_ROOT
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /var/lib/docker
        Requires=format-ephemeral.service
        After=format-ephemeral.service
        [Mount]
        What=/dev/disk/by-label/COREOS_ROOT
        Where=/var/lib/docker
        Type=ext4

    - name: nfs-server-bind.service
      command: start
      content: |
        [Unit]
        Description=Link /var/lib/docker/nfs to /srv/nfs
        Requires=var-lib-docker.mount
        After=var-lib-docker.mount
        Before=rpc-mountd.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/mkdir /var/lib/docker/nfs
        ExecStart=/usr/bin/ln -s /var/lib/docker/nfs /srv/nfs

    - name: rpc-mountd.service
      command: start
      enable: true

    - name: docker.service
      drop-ins:
        - name: 10-wait-docker.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount


