#cloud-config


hostname: swarmworker-{{ STR_REPLACE(".", "-", REMOTE_IP()) }}
ssh_authorized_keys:
  - {{ TRIM(FILE("/root/rsa_public_key")) }}

write_files:
  - path: "/root/worker_join_token"
    owner: core:root
    content: {{ TRIM(FILE("/root/worker_join_token")) }}

write_files:
  - path: "/root/rsa_public_key"
    owner: core:root
    content: {{ TRIM(FILE("/root/rsa_public_key")) }}

write_files:
  - path: "/etc/environment"
    permissions: '0655'
    owner: core:root
    content: |
      COREOS_PRIVATE_IPV4={{ REMOTE_IP() }}
      PXE_SERVER_IP={{ ENV("PXE_SERVER_IP") }}
      DHCP_RANGE={{ ENV("DHCP_RANGE") }}


coreos:
  units:
    - name: swarm-join.service
      command: start
      content: |
        [Unit]
        Description=Docker Master
        After=docker.service
        Requires=docker.service
        [Service]
        EnvironmentFile=/etc/environment
        ExecStart=/bin/bash -c "docker swarm join --token $(cat /root/worker_join_token) $PXE_SERVER_IP:2377 && docker run --net=host -e PXE_SERVER_IP={{ REMOTE_IP() }} -e DHCP_RANGE={{ ENV("DHCP_RANGE") }} -e MODE=WORKERJOIN -v /root/worker_join_token:/root/worker_join_token -v /root/rsa_public_key:/root/rsa_public_key --name coreos-pxe-swarm dermatthes/coreos-pxe-swarm"
