#cloud-config


hostname: swarmworker-{{ STR_REPLACE(".", "-", REMOTE_IP()) }}
ssh_authorized_keys:
  - {{ TRIM(FILE("/root/rsa_public_key")) }}

write_files:
  - path: "/root/worker_join_token"
    owner: core:root
    content: {{ TRIM(FILE("/root/worker_join_token")) }}


write_files:
  - path: "/etc/environment"
    permissions: '0655'
    owner: core:root
    content: |
      COREOS_PRIVATE_IPV4={{ REMOTE_IP() }}
      PXE_SERVER_IP={{ ENV("PXE_SERVER_IP") }}

coreos:
  units:
    - name: swarm-join.service
      command: start
      content: |
        [Unit]
        Description=Docker Master
        After=docker.service
        Requires=docker.service
        [Service]
        EnvironmentFile=/etc/environment
        ExecStart=/bin/bash -c "docker swarm join --token $(cat /root/worker_join_token) $PXE_SERVER_IP:2377"

    - name: format-ephemeral.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        After=sysinit.target
        Requires=sysinit.target
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/disk/by-label/COREOS_ROOT
        ExecStart=/usr/sbin/mkfs.ext4 -L COREOS_ROOT -F /dev/disk/by-label/COREOS_ROOT
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /var/lib/docker
        Requires=format-ephemeral.service
        After=format-ephemeral.service
        [Mount]
        What=/dev/disk/by-label/COREOS_ROOT
        Where=/var/lib/docker
        Type=ext4
    - name: docker.service
      drop-ins:
        - name: 10-wait-docker.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount


