#cloud-config

{{ INCLUDE("_inc/hostname.yml") }}
write_files:
  - path: "/etc/environment"
    content: |
      COREOS_PRIVATE_IPV4={{ REMOTE_IP() }}
      PXE_SERVER_IP={{ ENV("PXE_SERVER_IP") }}

ssh_authorized_keys:
  - {{ TRIM(FILE("/app/rsa_public_key")) }}
  - {{ TRIM(FILE("/app/id_rsa.pub")) }}

write_files:
  - path: "/root/worker_join_token"
    encoding: b64
    owner: core:root
    content: {{ TRIM(FILE("/root/worker_join_token")) }}

coreos:
  units:
    - name: swarm-join.service
      command: start
      content: |
        [Unit]
        Description=Docker Master
        After=sysinit.target
        Requires=docker.service

        [Service]
        ExecStart=/bin/bash -c "docker swarm join --tocken $(cat /root/worker_join_token) $PXE_SERVER_IP:2377"




