#cloud-config

{{ INCLUDE("_inc/hostname.yml") }}

ssh_authorized_keys:
  - {{ TRIM(FILE("/root/rsa_public_key")) }}
  - {{ TRIM(FILE("/root/id_rsa.pub")) }}

write_files:
  - path: "/root/worker_join_token"
    owner: core:root
    content: {{ TRIM(FILE("/root/worker_join_token")) }}

coreos:
  units:
    - name: swarm-environment.service
      command: start
      content: |
        [Unit]
        Description=SetEnvVars
        Before=docker.service

        [Service]
        Environment="COREOS_PRIVATE_IPV4={{ REMOTE_IP() }}"
        Environment="PXE_SERVER_IP={{ ENV("PXE_SERVER_IP") }}"

    - name: swarm-join.service
      command: start
      content: |
        [Unit]
        Description=Docker Master
        After=sysinit.target
        Requires=docker.service

        [Service]
        ExecStart=/bin/bash -c "docker swarm join --token $(cat /root/worker_join_token) $(echo $PXE_SERVER_IP):2377"




