#cloud-config

coreos:
  etcd2:
    proxy: on
    listen-client-urls: http://localhost:2379
    initial-cluster: etcdserver=http://{{ ENV("PXE_SERVER_IP") }}:2380

  fleet:
    metadata: "role=worker"
    etcd_servers: "http://localhost:2379"
  


{{ INCLUDE("_inc/hostname.yml") }}
{{ INCLUDE("_inc/ssh_authorized_keys.yml") }}
{{ INCLUDE("_inc/files.yml") }}


