



write_files:
  - path: "/bootpxe/rsa_public_key"
    content: {{ TRIM(FILE("/app/rsa_public_key")) }}

write_files:
  - path: "/home/core/.ssh/id_rsa"
    encoding: b64
    permissions: '0600'
    owner: core:root
    content: {{ BASE64_ENC(FILE("/app/id_rsa")) }}

write_files:
  - path: "/home/core/.ssh/id_rsa.pub"
    encoding: b64
    owner: core:root
    content: {{ BASE64_ENC(FILE("/app/id_rsa.pub")) }}
